apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: registry
type: Opaque
data:
  DB_USER: cmVnaXN0cnk=              # base64 encoded "registry"
  DB_PASS: cmVnaXN0cnkxMjM=          # base64 encoded "registry123"
  DB_NAME: cmVnaXN0cnk=              # base64 encoded "registry"
  JWT_SECRET: MjE2OGU3OGFkYWZjYTc2YTA1NjZmOGFiY2QwZWQxYWI1NTM0YmFmMjQzMTEwODhlZTBjZ
